#%RAML 1.0 NamedExample
Categories:  [{"id": 001,
              "name": "giftcard"},
              {"id": 002,
              "name": "office supplies"},
              {"id": 003,
              "name": "appliances"},
              {"id": 004,
              "name": "computers"}]
