#%RAML 1.0 NamedExample
product:  [{"id": 11,
 "name": "filter", 
 "barcode": "2346dftr", 
 "rate": "5.3", 
 "catagory": "plumbing"
              },
              {"id": 12,
 "name": "bolt", 
 "barcode": "2346dfdd", 
 "rate": "4.4", 
 "catagory": "hardware"
              }  ]