#%RAML 1.0 NamedExample
bill:
  [{"id":2,
  "num of items":20,
  "total cost":"$254.5",
  "total tax":"$12.5",
  "total value":"$267"
               },
               {"id":3,
  "num of items":3,
  "total cost":"30",
  "total tax":"$2",
  "total value":"$32"},
  {"id":4,
  "num of items":10,
  "total cost":"$100",
  "total tax":"$12",
  "total value":"$112"}]
               
